### ISSUE TITLE
Custom message for ArgumentOutOfRange exception

### ISSUE THREAD

**Issue by BrunoJuchli** [3komma14/Guard#21]
Allow extension methods for `IArg<T>` to set custom messages for `ArgumentOutOfRangeException`.
This requires adapting `IMessageHandler<T>`, so it has a method `void SetArgumentOutRange(string message)`.

This method could either replace the existing `SetArgumentOutRange(string message)` or complement it.

TODO:
 - [ ] define whether new method should replace existing method or not

**Comment by 3komma14** [comment]
Added new SetArgumentOutOfRange method with a message param.
