### ISSUE TITLE
Checking whether argument name is known is cumbersome

### ISSUE THREAD

**Issue by BrunoJuchli** [3komma14/Guard#22]
Currently everyone interested in whether the argument name is known must perform the following:

    string.IsNullOrEmpty(this._arg.Name))

Because messages should contain the argument name whenever possible, this kind of code may be duplicated a lot of times (also see #21 and #20).

I suggest amending the `IArg<T>` interface with a method:

    bool HasName { get; }

(which performs the string.IsNullOrEmpty check).

Alternatives:
 - If it's deemed acceptable to have the same message whether the argument is known or not, we could just replace the "null" argument name with "unknown".
 - Maybe one could also enforce that the argument name *must* be known at all times (throw an exception if it's not specified => implications on `Guard.That<T>(T argument, string argumentName = "")`)

TODO:
 - [ ] Determine which way to go (provide easier checking or make checking obsolete. If making checking obsolete => which way to go)

**Comment by 3komma14** [comment]
I have added the HasName to IArg interface.
