### ISSUE TITLE
Please use the [CallerMemberName] attribute

### ISSUE THREAD

**Issue by RehanSaeed** [3komma14/Guard#25]
You do not need to pass in the string name of the property, you might be able to use the [CallerMemberName] attribute.

**Comment by 3komma14** [comment]
That's correct for .Net 4.5 and later versions..
I will look into it, and see if there is a way to support older version of the framework also

**Comment by RehanSaeed** [comment]
I think I was tired when I wrote this, I don't think you can use this attribute as it will give you the method name of the caller and not the parameter.
